---
title: "scraping_familjeliv"
author: "Felix Lennert"
date: "2020-02-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rvest)
library(tidyverse)
library(purrr)
library(lubridate)
```

```{r}
mainpage <- "https://www.familjeliv.se"
```

First, number of pages must be evaluated manually:

```{r}
#browseURL(paste0(mainpage, "/forum"))
n_pages <- 1:4
```

Second, links to threads can be extracted:

```{r}
get_thread_links <- function(page_number) {
  thread_links <- character(length = 20)
  page <- read_html(paste0(mainpage, "/forum/latest/", page_number))
  thread_links <- html_nodes(page, ".thread a") %>%
    html_attr("href")
}

preliminary_list <- map(n_pages, safely(get_thread_links))
transp_preliminary <- preliminary_list %>% 
  transpose()

is_correct <- transp_preliminary$error %>% map_lgl(is.null)
numbers_error <- n_pages[!is_correct]
thread_suffixes <- unlist(transp_preliminary$result[is_correct])
```

The threads' number of pages need to be extracted as well:

```{r}
get_thread_page_numbers <- function(thread_suffix) {
  page <- read_html(paste0(mainpage, thread_suffix))
  temp <- html_nodes(page, ".last a") %>%
    html_attr("href")
  temp <- temp[19]
  n_pages <- str_extract(temp, "(?<=/)[^/]*$") %>%
    as.numeric()
  
  thread_number <- tibble(
    suffix = thread_suffix,
    n_pages = n_pages
  )
}

#test <- bind_rows(map(thread_links, get_thread_page_numbers))
```

Extract thread content:

```{r}
generate_links <- function(suffix, n_pages){
  mainpage <- "https://www.familjeliv.se"
  links <- character(length = n_pages)
  for (i in 1:n_pages){
    links[i] <- paste0(mainpage, suffix, "/", i)
  }
  links
}

extract_thread_content <- function(df) {
  suffix <- df[[1]]
  n_pages <- df[[2]]
  today <- as.character(lubridate::today())
  yesterday <- as.character(lubridate::today()-1)
  day_before_yesterday <- as.character(lubridate::today()-2)
  months_chr <- c("jan", "feb", "mar", "apr", "maj", "jun", "jul", "aug", "sep", "okt", "nov", "dec", "xyz")
  months_num <- c(1:12, 0)
  months_tbl <- tibble(
    months_chr = months_chr, 
    months_num = months_num
  )
  month_pattern <- paste(months_tbl$months_chr, collapse = "|")
  output <- tibble(
    date = as.Date("2020-02-22"),
    time = "abc",
    author = "abc",
    content = "abc",
  )
  output %<>% slice(0)
  quotes <- c()
  temp <- generate_links(suffix, n_pages)
    
  for (i in 1:length(temp)) {
    url <- temp[i]
    page_thread <- read_html(url)
    content <- html_nodes(page_thread, ".message-body , .first p") %>%
      html_text() %>%
      str_trim() %>%
      str_remove_all("\n") %>%
      str_remove_all("\t") %>%
      str_replace_all("[^[:alnum:]]", " ") %>%
      str_squish() %>%
      enframe(name = NULL) %>%
      rename(text = value) %>%
      slice(-1)
    text <- content[[1]]
    author <- html_nodes(page_thread, ".nick") %>%
      html_text() %>%
      str_remove_all("\n") %>%
      str_trim() 
    date <- html_nodes(page_thread, ".message-info") %>%
      html_text() %>%
      str_remove_all("\n") %>%
      str_trim() %>%
      str_split_fixed("×", 2)
    date_df <- as_tibble(date) %>%
      select(V1) %>%
      mutate(V1 = paste0(V1, "#0"))%>%
      mutate(time = str_extract(V1, "([0-2][0-9][:][0-5][0-9])"),
             post_number = map_chr(str_split(V1, "#"), 2),
             date = map_chr(str_split(V1, "([0-2][0-9][:][0-5][0-9])"), 1),
             date_numeric = case_when(str_detect(date, "Idag") ~ today,
                                      str_detect(date, "Igår") ~ yesterday,
                                      str_detect(date, "I förrgår") ~ day_before_yesterday),
             date_day = str_extract(date, "([0-3][0-9])|([0-9])"),
             date_year = if_else(str_detect(date, "([2][0][0-2][0-9])"),
                                 str_extract(date, "([2][0][0-2][0-9])"),
                                 "2020"),
             date_numeric = ymd(date_numeric),
             date_month_temp = if_else(is.na(date_numeric) == TRUE,
                                       str_extract(date, month_pattern),
                                       "0")) %>%
      left_join(months_tbl, by = c("date_month_temp" = "months_chr")) %>%
      mutate(date_month = if_else(date_month_temp == 0,
                                  month(date_numeric),
                                  months_num),
             date_day = if_else(is.na(date_day) == TRUE,
                                day(date_numeric),
                                as.integer(date_day)),
             date = paste(date_year, date_month, date_day, sep = "-")) %>%
      select(date, time) 
    date <- ymd(date_df[[1]])
    time <- date_df[[2]]
    quotes_temp <- html_nodes(page_thread, ".quote") %>%
      html_text() %>%
      str_remove_all("\n") %>%
      str_remove_all("\t") %>%
      str_replace_all("[^[:alnum:]]", " ") %>%
      str_squish() %>%
      unique()
    temp_df <- tibble(
      date = date,
      time = time,
      author = author,
      content = text
    )
      
    output <- bind_rows(output, temp_df)
    quotes <- c(quotes, quotes_temp)
  }
  
  for (j in 1:length(quotes)) {
    quotes[j] <- str_sub(quotes[j], start=-(2/3*str_length(quotes[j])))
  }
  output <- output %>%
    mutate(quote_bin = if_else(str_detect(content, "skrev.....................följande"),
                               1,
                               0),
           author = if_else(str_detect(author, "Anonym \\("),
                               NA_character_, 
                               author)) %>%
    distinct()
  output_w_quote <- output %>%
    filter(quote_bin == 1)
  output_wo_quote <- output %>%
    filter(quote_bin == 0)
  pattern <- paste(quotes, collapse = '|')
  output_w_quote$content_wo_quote <- character(length = nrow(output_w_quote))
  for (k in 1:nrow(output_w_quote)) {
    output_w_quote$content_wo_quote[k] <- str_split(output_w_quote$content[k], 
                                                    pattern = pattern, 
                                                    n = 2)[[1]][[2]]
  }
  output_w_quote$content_wo_quote %<>% str_squish()
  output_wo_quote$content_wo_quote <- output_wo_quote$content
  output <- bind_rows(output_w_quote, output_wo_quote) %>%
    distinct(content_wo_quote, .keep_all = TRUE) %>%
    arrange(date, time)
  return(output)
}
```



